# from: http://willmendesneto.github.io/2015/02/16/using-travis-ci-for-run-angularjs-unit-tests/

language: node_js

before_install:
  - 'export CHROME_BIN=chromium-browser'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass

node_js:
  - '0.12'
  - '0.11'

before_script:
  - 'npm install -g bower grunt-cli karma jshint'
  - 'bower install'

script: grunt
